Icelandic update (login screen, UI, dash)
Yellow-Dog-Man/Locale pull request #134
Opened 2023-11-04 07:03 UTC by Nammi-namm

Added many news strings, mostly login screen, UI, and corrected a few things to a more unified vocabulary where there used to be inconsistencies. Changed some words based on feedback (regarding ambiguity).

2023-11-07 01:59 UTC, Frooxius requested changes
I'd strongly suggest de-coupling changes for multiple languages, so they do not hold it up.

2023-11-07 01:59 UTC, Frooxius commented on en.json
> +        "Settings.LinuxIntegration": "GNU/Linux Integration",
Let's keep this colloquial please.

2023-11-07 05:01 UTC, Nammi-namm commented
Changed back as requested.

>I'd strongly suggest de-coupling changes for multiple languages, so they do not hold it up.

I'll keep this in mind thanks.

2023-11-08 05:32 UTC, Frooxius commented
Thanks, merging in!

2023-11-08 05:32 UTC, merged